// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuGlGvjl7IMhPz1lzdnFHkGToYdjD6ZXU',
    appId: '1:387431603408:web:e650920c815722883512d5',
    messagingSenderId: '387431603408',
    projectId: 'edtech-c5d59',
    authDomain: 'edtech-c5d59.firebaseapp.com',
    storageBucket: 'edtech-c5d59.appspot.com',
    measurementId: 'G-YLEQ9Y2YK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW-x96Ir5OV3Je6VDl1k2eg3ZYIRiAaTM',
    appId: '1:387431603408:android:c76c3c458a45f9d63512d5',
    messagingSenderId: '387431603408',
    projectId: 'edtech-c5d59',
    storageBucket: 'edtech-c5d59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTeWa04dC1FSqvQjkCMdthWVrjEsr-bbs',
    appId: '1:387431603408:ios:1759d2bd077107083512d5',
    messagingSenderId: '387431603408',
    projectId: 'edtech-c5d59',
    storageBucket: 'edtech-c5d59.appspot.com',
    iosBundleId: 'com.app.edtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTeWa04dC1FSqvQjkCMdthWVrjEsr-bbs',
    appId: '1:387431603408:ios:a8dc780b8cd2af4c3512d5',
    messagingSenderId: '387431603408',
    projectId: 'edtech-c5d59',
    storageBucket: 'edtech-c5d59.appspot.com',
    iosBundleId: 'com.app.edtech.RunnerTests',
  );
}
